name: uneme-cecosama-docs
services:
- name: documentation
  source_dir: /
  github:
    repo: tu-usuario/uneme-cecosama-docs
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt && mkdocs build
  run_command: python -m http.server 8080 --directory site
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: PYTHONPATH
    value: "."
  - key: MKDOCS_CONFIG_FILE
    value: "mkdocs.yml"

# Configuración de dominio (agregar después)
# domains:
# - domain: docs.uneme-cecosama.com
#   type: PRIMARY

# Auto-scaling configuration
scaling:
  min_instance_count: 1
  max_instance_count: 3